---
output:
  pdf_document:
    keep_tex: yes
  html_document: default
params:
  nbtest: 1500
---
```{r include = FALSE }
set.seed(7486)
f = function(m, n)
{ x = 1:n
   v = sample(x, m, replace=FALSE)
   teste = ( v == sort(v)) # sort(v) ordonne v
   z = 0
   if ( m == sum(teste)) { z = 1}
   return( z )
   }
simuleV = function(N, m, nV)
{ NV = rep(0, N)
   nL = length(nV)
   xV = rep(0, nL)
   for (i in 1:nL){
       for (k in 1:N){ NV[k] = f(m, nV[i])}
       xV[i] = sum(NV)/N }
   return(xV)
  }
```
Exercice 2
==================

pour N = `r params$nbtest`

```{r include = FALSE }
N <- params$nbtest
mV <- 2:8
pV <- 0*mV
l<- length(mV)
nV <- 10:30

for(i in 1:l){pV[i] <- mean(simuleV(N, mV[i], nV))}
P<-1/factorial(mV)

maxErreur<-max(abs(pV-P))
moyErreur<-mean(abs(pV-P))
```
---------------------------

```{r echo = FALSE, fig.cap="Probabilité de m numéro sur n dans le bon ordre"}
plot(mV, pV, xlab = "Taille de la suite d'entier ordonée", ylab ="rouge : proba exp. /bleu proba théo.)", col="red")
points(mV,P, col="blue")
```

>>Moyenne de $|pV-P|$ : $`r moyErreur`$.

>Pour N = 1500 l'expérience est $`r  0.0019446/moyErreur`$ proche de la théorie que pour N = 500

>>Max de  $|pV-P|$ : $`r maxErreur`$.

>Maximum de l'erreur entre la théorie et l'expérience

