---
output:
  pdf_document: 
    keep_tex: yes
  html_document: default
params:
  nbtest: 2000
---
```{r include = FALSE }
set.seed(7486)
p = function(n) 
{ x = 1:5
  return( prod(n - x)/(n^5) )
}
g = function(n)
{ x = 1:n
  z = 0
  v = sample(x, 6, replace=TRUE)
   if ( 6 == length(unique(v)) ) { z = 1}
  return( z )
}
simule = function(N, n)
{ NV = rep(0, N)
  x = 0
  for (k in 1:N){ NV[k] = g(n)}
  x = sum(NV)/N
  return(x)
}
```
Exercice 1 
==================

pour N = `r params$nbtest`


```{r include = FALSE }
N <- params$nbtest
nV <- 10:99
L <- length(nV)
xV <- 0*nV # Initialisation
yV <- 0*nV # Initialisation

#Changer le xV avec for (i in 1 :L) pour que xV[i] soit simule(N, nV[i])
for(i in 1:L){xV[i] = simule(N,nV[i])}

#Changer yV avec for (i in 1 :L) pour que yV[i] soit la probabilité exacte p(nV[i])
for(i in 1:L){yV[i] = p(nV[i])}
```
---------------------------
		
```{r echo = FALSE, fig.cap="Probabilité de 6 valeurs distinctes parmi n"}
#Faire un plot de (nV,xV) en bleu et de (nV,yV) en rouge dans la même figure.
plot(nV,xV, xlab = "n : cardinal de l'ensemble", ylab = "rouge : proba théo./bleu : proba exp.", col="blue")
points(nV,yV, col="red")
m<- mean(xV-yV)
d<-mean((xV-yV-m)^2)
```

>>Moyenne de $(xV-yV)$ : $`r m`$.

>pour N = 2000 l'expérience est $`r 0.0018534/m `$ plus proche de la théorie que pour N = 1000

>>Moyenne de $(xV-yV-m)^{2}$, variance de $(xV-yV)$ : $`r d`$.

>pour N = 2000 la dispersion est $`r  0.00012929459/d `$ plus faible que pour N = 1000

